### ISSUE TITLE
Centralized Error Handling

### ISSUE THREAD

**Issue by NadjibR** [parse-community/Parse-SDK-JS#1405]
### New Feature / Enhancement Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x] I am not just asking a [question](https://github.com/parse-community/.github/blob/master/SUPPORT.md).
- [x] I have searched through [existing issues](https://github.com/parse-community/Parse-SDK-JS/issues?q=is%3Aissue).

### Current Limitation
I was working on my app when suddenly it starts showing empty tables, by checking the network requests in my browser, I saw that the server is returning an error :
`{"code":209,"error":"Invalid session token"}`

Since my app make requests from all over the components to the server, it will be so hard to handle this error in all the requests and redirect the user the login page if the error 209 is returned !!

### Feature / Enhancement Description
I wonder if there is a way to centralize error handling, like session expired, invalid session token, or installation related errors, availibility of the server, ...

Or at least a well organized class object to initialize things, register subclasses, handle errors, ...
Check user session before every request would be a pain and overloads the server.

### Example Use Case
It's the point of my issue.

### Alternatives / Workarounds

Handle errors on every  get / save / find / destroy ....

### 3rd Party References

I'm not sure

**Comment by mtrezza** [comment]
Thanks for opening this issue!

An approach could be to handle each Parse Error in a method like `func handleParseError(e: ParseError)` instead of handling it in each try / catch or failed promise block.

I'm closing this as it does not seem to be a specific feature request.

For help with the Parse JS SDK, here are some resources you can try:
- For code-level questions we recommend Stack Overflow using the [parse-platform](https://stackoverflow.com/questions/tagged/parse-platform) tag.
- For network and server questions we recommend ServerFault using the [parse-server](https://serverfault.com/questions/tagged/parse-server) tag
- For questions that are not appropriate for the above mentioned sites we recommend our [community forum](https://community.parseplatform.org).

Feel free to comment if you have any questions and we can re-open this issue.
It seems you have already posted the same question in the Parse Community Forum.
