### ISSUE TITLE
Change default connection failure message

### ISSUE THREAD

**Issue by dblythy** [parse-community/Parse-SDK-JS#1469]
### New Feature / Enhancement Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x] I am not just asking a [question](https://github.com/parse-community/.github/blob/master/SUPPORT.md).
- [x] I have searched through [existing issues](https://github.com/parse-community/Parse-SDK-JS/issues?q=is%3Aissue).

### Current Limitation

If Parse JS SDK is unable to connect to the server, the error thrown is `'XMLHttpRequest failed: "Unable to connect to the Parse API"` which is rather confusing for client users.

### Feature / Enhancement Description

It would be good to change the default error message to something more helpful such as `Could not connect to the server` which non-technical users could understand. Or, allow JS SDK to specify custom error messages via something like `Parse.customError.101`

### Example Use Case

n/a

### Alternatives / Workarounds

n/a

### 3rd Party References

[related](https://github.com/parse-community/parse-server/issues/7915)

**Comment by mtrezza** [comment]
How about throwing the [Parse.Error](https://docs.parseplatform.org/js/guide/#client-only-errors):

> ConnectionFailed | 100 | The connection to the Parse servers failed.

I classified this as a bug, because we do have an explicit Parse.Error defined for this and it is not thrown.

This looks like a breaking change. If the error currently thrown has no error code, only the message, then someone parsing for that string (instead of comparing error codes as it should be) will have to change their client code, right?

**Comment by dblythy** [comment]
I will have to do some investigating
