### ISSUE TITLE
Remove Node 12 and 15 support

### ISSUE THREAD

**Issue by SebC99** [parse-community/Parse-SDK-JS#1535]
### New Feature / Enhancement Checklist
- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x] I am not just asking a [question](https://github.com/parse-community/.github/blob/master/SUPPORT.md).
- [x] I have searched through [existing issues](https://github.com/parse-community/Parse-SDK-JS/issues?q=is%3Aissue).

### Current Limitation
Current build settings allow for node.js from version 8. But as far as I can see, it can only be used via parse-server which only supports nodejs from version 12.

### Feature / Enhancement Description
Could we change node support for Parse SDK JS as well? It would allow using ES7 features as object destructuring without the need for a polyfill.

### Example Use Case
As an example, [these lines](https://github.com/parse-community/Parse-SDK-JS/blob/e08f3b6f85ac16ff57da00b044b70159eaea95c1/src/ObjectStateMutations.js#L119-L121) seems to be the slowest (by far) in Parse.Object getter, which is called a lot in any code. Replacing these lines with a simple `const data = {...serverData};` is more than 80% faster according to jsbench.

**Comment by mtrezza** [comment]
I'd suggest:
1. Create a PR which sets the min node version for the JS SDK to >=12 and refactors the bottlenecks you mentioned
2. Publish a minor release in Parse Server with the new JS SDK

Later, when we are bumping the node version to >=14 in Parse Server, we can also so that in the JS SDK. The bump to Node 14 in Parse Server will happen in 4 months with Parse Sever 6.x, at the end of the year.

**Comment by mtrezza** [comment]
A PR for this should cover:
- [ ] Remove support for Node 12 and 15
- [ ] Add `engines.node` to package.json, not sure why this is currently missing
- [ ] Update Node compatibility table in README
- [ ] Update Node badge table in README
