### ISSUE TITLE
Live queries, multiple subscription at once, is it me or it's not implemented at the moment?

### ISSUE THREAD

**Issue by avielfedida** [parse-community/Parse-SDK-JS#278]
Hello everyone, I'm using the **JS-SDK(v1.8.4)** with **Parse-server(v2.2.9)**, I tried to `subscribe` to multiple queries at the same app page, I've noticed that for example:

If I `subscribe` only to Query A, I can later `unsubscribe`(as in using the method) from Query A and all is good(no further events will emitted), but If I `subscribe` to Query A, then I again `subscribe` to Query B, and now I want to `unsubscribe`from Query A, **I can't**, events will still emitted.

If I `subscribe` to A then B, now I `unsubscribe` from B, no no further events will emitted for B, but I can't unsubscribe from A, I can call unsubscribe but events for A will emitted.

I don't know if this supposed to work like that(not implemented feature), anyway I just wanted to know if its a valid behavior?, for now the **workaround** is to delete the event from the subscription object, for example:

```
let subscription = (new Parse.Query('ObjectName')).subscribe();
subscription.on('create', data => {})
delete subscription ._events.create;
```

In the A, B case, you could use `unsubscribe` for B and `delete` for A.

**Update:**

To be more specific, if I have multiple queries subscribed to the same class, I can `unsubscribe` from both of them successfully, so it reduces the problem to a case where I have 2 queries with 2 different classes, if ever implemented?

**Comment by tyleralves** [comment]
I know this is a super old issue, but I'm seeing the same bizarre behavior.

Interestingly only the first subscription is incorrectly persisted:
```
this.subscriptionA = queryA.subscribe();
this.subscriptionB = queryB.subscribe()

this.subscriptionA.unsubscribe();  // Fails, subscription to queryA remains active
this.subscriptionA = queryA2.subscribe();
this.subscriptionA.unsubscribe(); // Succeeds; subscription to queryA2 is closed, but subscription to queryA remains active of course
```

**Comment by tyleralves** [comment]
Issue appears to be multiple simultaneous calls to `subscribe` don't wait for the first to set the default client. Each `subscribe` in a series of (practically) simultaneous calls will check for the default client, not find it, create a new client and overwrite the default. When you call unsubscribe it accesses that default client and your previous subscription doesn't belong to it.

Proper Workaround is to initialize the client before making any subscriptions
see: http://docs.parseplatform.org/js/guide/#livequeryclient

**Comment by tyleralves** [comment]
This happens because the sdk manages a live query client for you if you don't start your own manually. Unfortunately the `subscribe` method doesn't return a promise, or wait for the live query client to finish initializing before returning. So when you call `subscribe` multiple times in a row, it just overwrites the default LiveQueryClient repeatedly, leaving your previous listeners as zombies.  

Workaround:
Manually create a LiveQueryClient
See: http://docs.parseplatform.org/js/guide/#livequeryclient
**Note:** You must manually change your server url to `ws://` or `wss://`

**Comment by dplewis** [comment]
@acinader Thoughts on this one? Maybe create a `subscribeAsync()` function.

Also just realized that you can't pass sessionToken into query.subscribe();

**Comment by acinader** [comment]
Certainly sounds like an issue for any reasonably complex use.

Step one would be failing unit tests for his example.  Not sure what the implementation would be as I am not familiar with that bit of code (yet ;)), but this is a clearly written issue with enough info to create failing tests, which would like lead to the solution being apparent?

**Comment by Amphaal** [comment]
Hi guys,

It's been a long time since i haven't played with Parse but I think I can help. 

I had trouble back in 2018 to make livequeries work well with a moderately complex project involving React-native / Redux / RxJS : looking at our PA issue, it's seems related to my old concerns.

Following my proposal on #533 , i did a hasty fix on LiveQuerySubscription.js and ParseLiveQuery.js, modifying the open/close/subscribe/unsubscribe methods. It fixed everything if i remember correctly.

I can, if you like, try a diff and propose a merge.

**Comment by dplewis** [comment]
@Amphaal That would be great! It looks l at your proposal and you found the root cause.
