### ISSUE TITLE
Migration of app which uses 1.5.0 version of Parse JS SDK

### ISSUE THREAD

**Issue by anipapyan** [parse-community/Parse-SDK-JS#360]
My Backbone app uses 1.5.0 version of Parse JS SDK and I cannot update it to the latest versions because there is no Backbone support after 1.5.0, e.g. unable to use Parse.Collection class after 1.6.0 (as Parse object is not defined anymore) which is the main method I implemented the collections in my code. 
But migration guide requires to use Parse JS SDK at least with 1.6.14 version in order to have ability to change the server URL.
Is there a plugin I can use in order to have ability to change the URL while using Parse JS SDK 1.5.0 or another plugin which will allow me to use the Parse object and its classes when using  >1.6.14 Parse JS SDK?

**Comment by typhonrt** [comment]
@anipapyan I do have a solution [backbone-parse-es6](https://github.com/typhonjs-backbone-parse/backbone-parse-es6). The nice thing is that it has the latest released version of Backbone 1.3.3 working with Parse 1.6+. A caveat is that it doesn't play nice with RequireJS right now due to a workaround. You can read about that in https://github.com/typhonjs-backbone-parse/backbone-parse-es6/issues/8 and the related #144. 

It works great with JSPM and other modern package managers. It would take a small fix in the Parse JS SDK to get it working with RequireJS smoothly; see #144.
