### ISSUE TITLE
Live query + Cordova: does not sync differences after reconnect

### ISSUE THREAD

**Issue by rooswelt** [parse-community/Parse-SDK-JS#403]
I'm on  a Cordova app and Parse JS SDK 1.9.2.

Live query works fine while application is in foreground and stops working in background (and that's ok)

If any events occurs while in background they are not retrieved. Is there a way to avoid this?

**Comment by dstarke** [comment]
What I try to do is detect the reconnection (which you can do with the `open` event on the subscription), and issue a query for any objects I might have missed.

You can probably do a little better in the browser if you also pay attention to `window.online` and `window.offline` events where available, and tear down and recreate your connection and subscription state appropriately, since the exponential back off for connections can take a lot longer to figure out that your connection has been restored.
