### ISSUE TITLE
Doesn't work with RN 0.43

### ISSUE THREAD

**Issue by pewh** [parse-community/Parse-SDK-JS#418]
When I start RN package, it shows an error:
```
Loading dependency graph, done.
error: bundling: UnableToResolveError: Unable to resolve module `react-native/Libraries/react-native/react-native.js` from `/home/ryan/Documents/StikerMob/node_modules/parse/lib/react-native/StorageController.re
act-native.js`: Module does not exist in the module map or in these directories:
  /home/ryan/Documents/StikerMob/node_modules/react-native/Libraries/react-native

```

**Comment by andrewimm** [comment]
React VR will be tracking every 2 versions of React Native. The latest version supports RN 0.42, and the next version we will support is 0.44.
If you create a new project with the react-vr CLI, it should explicitly target `react-native@0.42.x` and not install 0.43

**Comment by andrewimm** [comment]
Will look into this when I have some time

**Comment by pewh** [comment]
Nevermind. I already fix this by following https://github.com/ParsePlatform/Parse-SDK-JS/issues/342#issuecomment-243890242. Thank you.

**Comment by flovilmart** [comment]
@pewh let's keep this open as this require a correct fix.

**Comment by andrewimm** [comment]
If you're using RN, a library like github.com/andrewimm/parse-lite is much better suited to React applications.

**Comment by flovilmart** [comment]
@andrewimm that's a really nice little lib you got here :)

**Comment by oallouch** [comment]
Whi not give this lib a boost buy adding it as an official client and adding its doc on http://parseplatform.org/ ?

**Comment by flovilmart** [comment]
@oallouch the docs and homepage repos are open source! Feel free to add it there :)

**Comment by oallouch** [comment]
This looks very interesting, even if I'm not using it right now. @andrewimm I can only imagine the need for a lot more utility functions to manager all the local Pointer resolutions. For instance, in my app, I have a tree of Parse.Objects and the official js sdk makes it very easy to include nested branches.
Anyway, I still feel guilty when storing Parse.Objects in my Redux store...next to an artificial version number that I increment whenever I modify the Parse.Object, so that my connected components update themselves.

**Comment by alejonext** [comment]
In the file `APP/node_modules/parse/lib/react-native/StorageController.react-native.js:14`  is
```
import { AsyncStorage } from 'react-native/Libraries/react-native/react-native.js';
```

But the libraries, no exists... Is exist

```
import { AsyncStorage } from 'react-native';
```
