### ISSUE TITLE
Need Backbone support for latest SDK

### ISSUE THREAD

**Issue by mohansn** [parse-community/Parse-SDK-JS#43]
I am currently building an backbone app (items added to a table for each Google form submitted for review). I am on parse 1.2.13 JS SDK.

Migrating to 1.6 will obviously mess up my working code since there is no Collection class.

I am somewhat new to web development. Could someone let me know if Backbone support is in the works or if there is a simple workaround?

Thanks!

**Comment by typhonrt** [comment]
There is no simple workaround and Parse / FB is not going to do it because you know React! Good news is that I'm almost done with creating a Backbone fork 1.2.3 that works fully with Parse 1.6. About 95% of the way there at this point pending a little more testing. Nice thing too is that I modularized Backbone  and made it ES6. I'll also be distributing ES5 bundles meant to be consumed in various module systems (RequireJS, SystemJS, etc.) along with a bundle meant for global usage.

**Comment by mohansn** [comment]
Thanks a million, @typhonrt ! Looking forward to it.

**Comment by cfoulston** [comment]
My app just came to a screeching halt because of this. Looking forward to your implementation  typhonrt.

The least Parse could do is provide a migration guide or something.

**Comment by typhonrt** [comment]
@cfoulston Thanks for reminding me of this issue... 

I've had the repos up for a week or so, but have been polishing off documentation and I have still to get a repo up for a full SystemJS / JSPM demo which is a great way to consume the ES6 source. If you want to check things out though the Backbone-Parse-ES6 repo is: https://github.com/typhonjs/backbone-parse-es6

The `/dist` directory has various ES5 bundles for AMD, CJS, and global consumption.

If you weren't using Backbone / Parse previously with a module system you'll want to choose the global bundles. The basic global bundle has Backbone & Parse. You'll need to load Underscore & a jQuery equivalent via script tags before the backbone-parse library. The "global inclusive" bundle also contains Underscore and jQuery. 

and the main SystemJS / JSPM + global demo will be up here before the end of the week most likely:
https://github.com/typhonjs/backbone-parse-es6-demo

Technically you should be able to use things just like before and I have a whole framework on top of Backbone that works, but that doesn't mean I have all the angles tested. I'm going to be updating to Backbone 1.2.4 / or the next latest release and port over all of the tests from the original Backbone repo at that time and also see if I can come up with some way of auto-testing Parse thoroughly.

Drop an issue in the repos for questions.

**Comment by midhunanew** [comment]
@typhonrt I have an old parse project which uses JS SDK 1.2.12, Can I use your library as a drop in replacement for parse library? I'm already using require-js for my modules like,

```
define(
[
	'jquery',
	'underscore', 
	'parse',
	'models/Comment',
	'collections/Comments'
], function($, _, Parse, Comment, Comments)
{
}
);
```

Do I need to make code changes in every files to get it work with new parse open-source server?

**Comment by typhonrt** [comment]
Unfortunately RequireJS support is a bit challenging. There is an existing issue: https://github.com/typhonjs-backbone-parse/backbone-parse-es6/issues/8 regarding RequireJS support where I detail the problem. A small change to the Parse JS SDK could solve the problem: https://github.com/ParsePlatform/Parse-SDK-JS/issues/144, but @andr

**Comment by midhunanew** [comment]
@typhonrt Thank you so much for the prompt response. Could you please point a PR or add somewhere the changes required in Parse JS SDK, so we can continue with [AMD module](https://github.com/typhonjs-backbone-parse/backbone-parse-es6/tree/master/dist/amd) from your repo?

**Comment by typhonrt** [comment]
We'll my hands are tied as I'm not involved with Parse and #144 has gone without answer or confirmation from @andrewimm for months, so a PR is pointless as it will just sit by the wayside as well most likely. There is a simple solution; `Parse.encode = encode; Parse.decode = decode;` in [Parse.js](https://github.com/ParsePlatform/Parse-SDK-JS/blob/master/src/Parse.js), but if I can't get FB to acknowledge it then it's beyond what I can do personally. I already provided the [only community solution](https://github.com/typhonjs-backbone-parse/backbone-parse-es6) to the outright abandonment of Backbone in regard to Parse. 

It works great for modern package managers such as JSPM presently. It's not like I don't want to support legacy solutions like RequireJS as well, but such is life. Upgrading your web app while taking more work to use JSPM, Webpack, etc. will solve things. I've posted the solution above, but it's a crapshoot if FB will add it to the JS SDK. 

Unfortunately the solution to https://github.com/typhonjs-backbone-parse/backbone-parse-es6/issues/5 outweighs the side effect of breaking easy RequireJS support, but once again a small modification to the Parse JS SDK would allow things to proceed with full RequireJS support out of the box. Contact the Parse team and let them know you'd like to see this solved.

**Comment by midhunanew** [comment]
I'm using [parse-bone](https://www.npmjs.com/package/parsebone) with require-js with few modifications to remove the wrapper and it is working as expected. Thanks for your support @typhonrt

**Comment by typhonrt** [comment]
@midhunanew parse-bone may work for now and is the best drop in replacement, but likely won't see much further progress. I guess the difference with https://github.com/typhonjs-backbone-parse/backbone-parse-es6 is that I am supporting the latest Backbone release and updates and you can use the latest version of the Parse JS SDK.

The problem I outlined above is that to get nested pointer relationships to encode / save correctly I have to directly access the [encode file of the Parse JS SDK](https://github.com/typhonjs-backbone-parse/backbone-parse-es6/blob/master/src/BackboneParseObject.js#L4). This makes usage in RequireJS a bit messy. I haven't tried all too hard to get it working as well I don't need that functionality as modern package managers solve the problem transparently. I gather one can duplicate the parse JS SDK to create a hack workaround with RequireJS, but it's not clean per se. I'm not getting paid for any of this so can't exactly focus on this since there is such an easy solution if the Parse JS team takes my suggestion up for consideration. The problem is that encode.js references a bunch of other internal Parse JS files and the dependencies continue to chain up to foul things up w/ RequireJS. If it were exposed via Parse.js / ala `Parse.encode(...)` there would be no problem.

**Comment by lockwobr** [comment]
So I know that this a bit old but was able to fix a lot of the bugs in are parse code by doing this close to start of the page load. Hope this helps other solve this problem.


	define (['underscore', 'parse', 'backbone'],  function (_, Parse, Backbone) {
		Parse.Collection = Backbone.Collection;

		function extend(obj, destination, source) {
			
			for (var k in source) {
				if (!destination.hasOwnProperty(k)) {
					obj[k] = source[k];
				}
			}
	  		return obj; 
		};

		// add all methods that are in backbone and not in parse, to make it more like the old parse library
		extend(Parse.Object.prototype, Parse.Object.prototype, Backbone.Model.prototype);

	       var models = {};
	       models.Campaign = Parse.Object.extend({
	       // parse model logic 
	       });
	     
	    return models;
	});
