### ISSUE TITLE
Any schedule on fulltext search?

### ISSUE THREAD

**Issue by SebC99** [parse-community/Parse-SDK-JS#452]
It's enabled on parse-server since 2.5.0 and through REST, but do you have any schedule on JS SDK (to be used on parse-server side)?
It would allow to have it on any clients through cloud functions.

(sorry I can't do any PR myself)

Thanks!

**Comment by dplewis** [comment]
Support for text and compound indexes will be added to parse-server so users don't have to add their own indexes.

Discussion
https://github.com/parse-community/parse-php-sdk/pull/333

**Comment by flovilmart** [comment]
Closing as in progress.

**Comment by seriph** [comment]
@SebC99  I've had this working since April and just updated it to be in synch with the latest version of the JS SDK. You're welcome to use the following until we get it merged in:
https://www.npmjs.com/package/parse-text
The syntax is just Query.text(<column>, <text query>, <options>)
If you're using Mongo, I would recommend using the following as well. It's the latest version of the Parse Server, but will work properly for compound text indices (you have to create them yourself).
https://www.npmjs.com/package/parse-server-text
