### ISSUE TITLE
Recommend Security procedures for Anon Users to write data.

### ISSUE THREAD

**Issue by gateway** [parse-community/Parse-SDK-JS#472]
Please mark as discussion:

We are working on a simple widget that will be on our website or be abled to be embedded on others sites.  Its a simple star rating widget that allows an anonymous user to click on a rating and that gets submitted to our parse backend.  (btw we are doing way more with our Native clients for iOS/Android) but need a small JS version.

The concern here after reading https://www.webniraj.com/2013/08/01/using-the-parse-javascript-sdk-be-careful/ sort of makes me not want to do this.  I have read though the old blog posts of parse security and http://blog.parse.com/announcements/protect-user-data-with-new-parse-features/ for anon users.  

Question is if you have an anon users thats able to write to lets say voting class, be able to use the dev console to spam or post more votes via parse query calls?  We will have an ACL set up with a custom role called Anon that will have write only but need some pointers or should we not do this at all.

**Comment by flovilmart** [comment]
You should probably ask on stackoverflow as this issue is not related to parse server but any voting system where a random user can write to your database. Just to get you started on the problematics you face, you'll probably need to:

- Implement rate limiting (by IP or other means)
- Prevent client class creation.
- Implement proper CLP / ACL's for your votes
- Implement CLP properly for all your objects
...

OR, just write a HTTP endpoint that casts the vote an do not expose Parse to the JS client...

**Comment by gateway** [comment]
Ill just opt for our own http endpoint and rate limit with express-brute and be done with it.. thanks!
