### ISSUE TITLE
Full Text Search

### ISSUE THREAD

**Issue by dblythy** [parse-community/Parse-SDK-JS#476]
Any news on when query.fullTextSearch will be available?

Cheers

**Comment by seriph** [comment]
@dblythy I've had this working since April and just updated it to be in synch with the latest version of the JS SDK. You're welcome to use the following until we get it merged in:
https://www.npmjs.com/package/parse-text
If you're using Mongo, I would recommend using the following as well. It's the latest version of the Parse Server, but will work properly for compound text indices (you have to create them yourself).
https://www.npmjs.com/package/parse-server-text

**Comment by dplewis** [comment]
@dblythy There is a PR pending https://github.com/parse-community/Parse-SDK-JS/pull/470, Don't know why that one hasn't been merged yet.

**Comment by russell-dot-js** [comment]
I just reviewed #470, could use a little cleanup prior to merge IMO

**Comment by montymxb** [comment]
We're all good, full text support has been merged. Once the next release rolls out everyone will be able to utilize this. Still pending formal docs update to our [js docs](http://docs.parseplatform.org/js/guide/), which may precede the release of this feature.
