### ISSUE TITLE
docs comments

### ISSUE THREAD

**Issue by oallouch** [parse-community/Parse-SDK-JS#516]
Hi,
I'm glad the docs are getting some love. For me, that was the weak point of parse-server...but :
. when I select a Class, I really miss having a list of function members
. where can I find the Cloud Code function/hook/job request and response arguments ? I think that was the most incomplete part of the docs (eg: the new "headers" property was missing). My guess is it's coming as a new Cloud Code API Reference page. Am I wrong ?
I really wish there'll be a new "Docs" paragraph title on each release changelog and PR can be refused because of missing docs update.

Anyway, congrats on the docs.

Olivier

**Comment by flovilmart** [comment]
>  I really miss having a list of function members

I need to check if jsdoc can add the list of members as a summary

> where can I find the Cloud Code function/hook/job request and response arguments

We need to add it, probably in the same page

I need to check if that's possible

**Comment by rorz** [comment]
I came here to say something similar about the function members. But I feel bad for having a 'moan' at the maintainers because I am *so* thankful (words can't explain) for the post-opensourcing work that has gone into the platform.

For me, it's a minor gripe that would be great if it could get fixed at some point... I've never worked on docs before, but if it's something you could point me in the direction of — I'd love to help(?)

Also, I've been using [devdocs](devdocs.io) a bunch recently, and the browser-app is stellar... Perhaps we could also look at getting the Parse (JS) SDK implemented there? [(as per here)](https://github.com/Thibaut/devdocs/wiki/Adding-documentations-to-DevDocs)

**Comment by flovilmart** [comment]
@rorz Eheh, thanks for the kind words, I'm all open for being on dev-docs and even use another docs generation tool (like documentation.js) My rush was to get the latests docs out, and yes there are some rough edge, the Cloud Code interfaces should probably be exposed also in this docs, not sure how to generate a doc for methods that are not implemented ;)

It's quite easy to get started, @rorz , just run `npm run docs`  and it will generate the docs in the `out` folder (not committed). Then it's pretty easy to browse and see them

**Comment by flovilmart** [comment]
How do you like this layout: https://flovilmart.github.io/parse-js-docs-demo/index.html

Using the [minami](https://github.com/Nijikokun/minami) template. All function are properly exposed.

**Comment by flovilmart** [comment]
I found a way also to define all the Cloud Code methods in an empty file, that will help documenting them.

**Comment by oallouch** [comment]
Looks good.
Can this template sync both frames so that we only get members of the current Class ?

**Comment by flovilmart** [comment]
I haven’t look into the docs of this template, so no way to know for sure

**Comment by flovilmart** [comment]
@oallouch we've updated the template generation, for now, the navigation on the left is still a bit 'static'.

I managed to add CloudCode docs, http://parseplatform.org/Parse-SDK-JS/api/master/

(missing a few things still but we're getting there)
