### ISSUE TITLE
Typescript definitions @types/parse need to be kept up to date

### ISSUE THREAD

**Issue by TimNZ** [parse-community/Parse-SDK-JS#528]
I submitted a pull to add Parse.liveQueryServerUrl to DefinitelyTyped repo, but it would be nice if that was part of the deployment workflow

**Comment by yomybaby** [comment]
👍

**Comment by dplewis** [comment]
This was tried discussed before in a PR https://github.com/parse-community/Parse-SDK-JS/pull/388
 
As I understand it since this isn't a typescript repo we can't push autogenerated files to @types/parse

An alternative would be to autogenerate a file with [dts-gen](https://github.com/Microsoft/dts-gen) and submit types on release

Before that can happen two issues exists

`Cannot assign to 'serverURL' because it is a read-only property.`

https://github.com/DefinitelyTyped/DefinitelyTyped/blob/cbe76dfa861ea28b07433c119d9cf4505c49aa0d/types/parse/index.d.ts

I don't know why this happens as serverURL isn't readonly in the @type/parse but can be fix with the following workaround.

`(Parse as any).serverURL = '';`

The second issue is that prototypes would be generated. There is a PR opened to address this https://github.com/Microsoft/dts-gen/pull/115

@agoldis @flovilmart @acinader @TimNZ Thoughts?

**Comment by agoldis** [comment]
Good idea! I am not sure about the quality of [dts-gen](https://github.com/Microsoft/dts-gen) output though, it might be worse than we currently have. 

Additional aspect is version upgrades - this requires some manipulation to the files structure of typedefs package, those are not frequent though and prob can be handled manually. 

@dplewis we can try to run `dts-gen` it to see if it is good enough. I never used it before, will try to compare during the weekend.

**Comment by dplewis** [comment]
I tried it and it works if you erase the prototype definitions (PR is waiting for approval). The readonly serverURL error still existed tho.

**Comment by agoldis** [comment]
@dplewis sorry I didn't have chance to explore this option. Any chance you can publish / gist the output you've got?

**Comment by dplewis** [comment]
Wheres the gist [parse.d.ts](https://gist.github.com/dplewis/2ffa7f9175337728a653b8f963a4ffe1)

To generate parse globally `npm install parse -g`, then run `dts-gen -m parse`

**Comment by agoldis** [comment]
Thanks, @dplewis.
At glance, it isn't able to recognize argument types and abuses `any` usage. on the other hand it recognizes classes and methods quite well...

To summarize, IMO:
1. I don't think we can sacrifice already existing detailed definitions.
2. It does provide quite a lot of information about new / removed entities (methods, classes etc.)

What do you think about some hybrid process that wouldn't touch whatever is already there, but create a PR / notify about additions and / or detected changes?
