### ISSUE TITLE
ACL is not fetched when I use "select"

### ISSUE THREAD

**Issue by Samigos** [parse-community/Parse-SDK-JS#571]
Parse Server: 2.7.4

I have an `or` query and I want to add some additional constraints to it, like so:

```
var chatRoomQuery = Parse.Query.or(currentUserAsSenderChatRoomsQuery, currentUserAsReceiverChatRoomsQuery);

chatRoomQuery.include(["sender.school"], ["receiver.school"]);
chatRoomQuery.select("lastMessage", "lastMessageWasAddedAt", "senderChatRoomName", "receiverChatRoomName", "hasSenderLeft", "hasReceiverLeft", "sender.gender", "sender.school", "receiver.gender", "receiver.school");
```

As you can see, I use the `select` constraint... I realised though, that when `select` is being used, `ACL` is not a part of the fetched object(s), even if I explicitly add it, like so:

```
chatRoomQuery.select("ACL", lastMessage", "lastMessageWasAddedAt", "senderChatRoomName", "receiverChatRoomName", "hasSenderLeft", "hasReceiverLeft", "sender.gender", "sender.school", "receiver.gender", "receiver.school");
```

Any idea why's this happening? What could I do to as a workaround?

**Comment by flovilmart** [comment]
This is a bug. Are you willing to write a failing Test and open a pull request with it? We’ll be able to fix it soon.

**Comment by Samigos** [comment]
I want to, but I have no idea how! Is there a guide or something?

**Comment by flovilmart** [comment]
@Samigos you can check our contributing guide:

https://github.com/parse-community/parse-server/blob/master/CONTRIBUTING.md

As well as all other specs in this file for example: https://github.com/parse-community/parse-server/blob/master/spec/ParseQuery.spec.js#L3002

**Comment by georgesjamous** [comment]
I believe in Parse-Server, ACL include is enforced (as well as ObjectId, createdAt, updatedAt ..)
check : [Line where key is enforced in Parse-Server](https://github.com/parse-community/parse-server/blob/1afc34eea3081a5a2c105da1b9d25ba26a5de60e/src/RestQuery.js#L8)

I think the problem resides in JS-SDK
here [function handleSelectResult](https://github.com/parse-community/Parse-SDK-JS/blob/0fbc604c52d54e4cb7828afe4cd9f75fd844fa6a/src/ParseQuery.js#L72)
specifically on [select.forEach((field)](https://github.com/parse-community/Parse-SDK-JS/blob/0fbc604c52d54e4cb7828afe4cd9f75fd844fa6a/src/ParseQuery.js#L75)
where we are looping though the selected keys only.
Additional keys added by the server (in your case ACL) are ignored, but I don't think it should be fix here !.

I think the main issue  is happening [here](https://github.com/parse-community/Parse-SDK-JS/blob/0fbc604c52d54e4cb7828afe4cd9f75fd844fa6a/src/ParseObject.js#L1357)
I am not sure why, but, for it to work `otherAttributes` should contain ACL but it may be filtered out by `if (attr !== 'className' && attr !== '__type') {`

I think, It is working for createdAt & updatedAt since the getter function in Parse.Object access the json directly.

@Samigos  _I just took a quick look, I am not sure that what I said is 100% correct. This should help you target bug_

I will take a stab at it in a couple of days if I have the time

**Comment by cipiripper** [comment]
You can select ACL with a dumb workaround: 

```
query.select([ '_rperm', '_wperm']);
```

This is how they are stored in MongoDB, and will be passed on to it. Mongo will return those two, and Parse will convert them into ACL objects.

**Comment by flovilmart** [comment]
I pushed a fix, this is gonna be part of the next release of parse-server. ACL's will always be included.
