### ISSUE TITLE
doesNotMatchKeyInQuery doesn't work when using same query and key with different query key

### ISSUE THREAD

**Issue by tgreco** [parse-community/Parse-SDK-JS#621]
My schema: 

 ```
Match: 
scheduledBy (Pointer to user) 
scheduledWith (Pointer to user)

Photo: 
owner (Pointer to user)
```

I want to find photos for users that do not have any matches. 

What I tried:

        
```
 let photoQuery = new Parse.Query(MODEL.Photo.className());
photoQuery.include('owner');

// Do not include people who have matches
let matchQuery = new Parse.Query(MODEL.Match.className());
photoQuery.doesNotMatchKeyInQuery('owner', 'scheduledBy', 	matchQuery);
photoQuery.doesNotMatchKeyInQuery('owner', 'scheduledWith', matchQuery);

// Get final results
return photoQuery.find()
```

This only works for the scheduledBy column.

Seems like you can't do doesNotMatchKeyInQuery with the same key and query but different query keys for some odd reason.

Can anyone confirm this? If so what would be the best alternative?

I removed scheduledBy and used scheduledWith only and that worked as well.  So it's not something wrong with the data it's a bug with Parse I believe.

**Comment by flovilmart** [comment]
Thanks for your question!

We want to make sure to keep signal strong in the GitHub issue tracker – to make sure that it remains the best place to track issues that affect the development of Parse Server.

Questions like yours deserve a purpose-built Q&A forum. Would you like to [post this question to Stack Overflow with the tag #parse.com](http://stackoverflow.com/questions/tagged/parse.com)? We'll be happy to answer there. Post a link to your Stack Overflow question here, so that we don't lose track of it.

You may also use [Server Fault](https://serverfault.com/tags/parse) for questions about managing your own servers.

**Comment by tgreco** [comment]
https://stackoverflow.com/questions/51663576/parse-cloud-code-doesnotmatchkey

**Comment by tgreco** [comment]
@dplewis my issue with a compound query is that this query is much more complex and uses GeoPoints and near in a subquery so I cannot include that in my compound query as the documentation says: 

> Note that we do not support GeoPoint or non-filtering constraints (e.g. near, withinGeoBox, limit, skip, ascending/descending, include) in the subqueries of the compound query.

```
let matchQuery = new Parse.Query(MODEL.Match.className());

let photoQuery1 = new Parse.Query(MODEL.Photo.className());
photoQuery1.doesNotMatchKeyInQuery('owner', 'scheduledBy', 	matchQuery);

let photoQuery2 = new Parse.Query(MODEL.Photo.className());
photoQuery2.doesNotMatchKeyInQuery('owner', 'scheduledWith', matchQuery);

// Contains all default photos of people without matches 
let compoundPhotoQuery = new Parse.Query.and(photoQuery1, photoQuery2);

// TODO: mainPhotoQuery.matches(compoundPhotoQuery); ?
```

How could I include compoundPhotoQuery into the main PhotoQuery now? 
I'm not sure it's possible to do a matchesQuery or containedIn on the actual object rather than a specific key in the object is there?
