### ISSUE TITLE
ReferenceError: regeneratorRuntime is not defined

### ISSUE THREAD

**Issue by dplewis** [parse-community/Parse-SDK-JS#717]
Using parse through CDN or `npm install parse@version` works

I get the following error `ReferenceError: regeneratorRuntime is not defined`

If I try to run get the bleeding edge in a node project

`npm install parse-community/Parse-SDK-JS.git#master --save`

or 

build it myself and copy parse.min.js from the dist folder into a simple html file.

I don't know much about babel to fix the issue

**Comment by farhansyed9** [comment]
Also have this issue, did you find a solution?

**Comment by dplewis** [comment]
I haven't you can try playing around with babel to see if you can get it to work

**Comment by agoldis** [comment]
Facing the same issue with [Parse@2.2.0](https://www.npmjs.com/package/parse)

https://github.com/parse-community/Parse-SDK-JS/blob/master/gulpfile.js#L18 specifies `@babel/plugin-transform-runtime` [configuration option](https://babeljs.io/docs/en/babel-plugin-transform-runtime#regenerator):
```
regenerator: false
```

That instructs babel to transpile `async` functions into a code that assumes existence of globally defined `regeneratorRuntime`.

When you start to use the SDK in a project that *does not* define a global `regeneratorRuntime` you'll bump into the exception.

There are some workarounds, but appropriate solution highly depends on your project's specific configuration>

1. Manually include `regeneratorRuntime`
Use https://www.npmjs.com/package/regenerator-runtime and make sure the following code is executed **before** Parse is initialized:

```
import regeneratorRuntime from 'regenerator-runtime/runtime';
window.regeneratorRuntime = regeneratorRuntime;
```

2. Use babel to try and inject the variable
Use [`@babel/polyfill`](https://babeljs.io/docs/en/babel-polyfill) together with [`@babel/preset-env`](https://babeljs.io/docs/en/babel-preset-env) + customize the option [`useBuildIns`](https://babeljs.io/docs/en/babel-preset-env#usebuiltins) to inject required polyfills. That's quite tricky, though and very implicit.

### For maintainers
If there's no specific reason to use this option [here](https://github.com/parse-community/Parse-SDK-JS/blob/master/gulpfile.js#L18), I would suggest to set it to `true`. That will cause babel to use `@babel/runtime/regenerator` instead of a global variable, which is much easier to set up (as described in [`generatorAliasing`](https://babeljs.io/docs/en/babel-plugin-transform-runtime#regenerator-aliasing))

**Comment by robertoin** [comment]
Why does this error appear? Everything was working fine to me last week and now I have this issue too.

**Comment by dovk** [comment]
Same here - I uninstalled **parse@2.2.0** and installed **parse@2.1.0 --exact** and it's back to normal

**Comment by fmendoza** [comment]
Revert to 2.1.0 is the workaround for now.

**Comment by brianyyz** [comment]
For newbies to the Parse JS SDK (like me) I reverted to the 2.1.0 level of the parse.min.js script by retrieving it from:

`https://npmcdn.com/parse@2.1.0/dist/parse.min.js `

placed it in a local js directory and updated the script tag to refer to it instead of the npmcdn server.
