### ISSUE TITLE
Any chances of releasing an Angular version of the SDK?

### ISSUE THREAD

**Issue by gfpacheco** [parse-community/Parse-SDK-JS#8]
Angular is one of the most popular front end frameworks nowadays. I would love to be able to use Parse in my Angular web app and not have to use third-party wrappers (or in my case, have to write your own)

**Comment by mandazi** [comment]
@gfpacheco: Theoretically couldn't you use the Parse REST API with the Angular JS web application?

**Comment by andrewimm** [comment]
With this open sourcing of the SDK, we've designed it to be the core of any application, letting developers wrap it with bindings for the framework of their choice. The hope is that between official Parse bindings (such as Parse+React, launched last April) and community-driven bindings, we'll be able to support a variety of popular frameworks, scalably. Frameworks develop fast, and we don't want to tie releases of the SDK to those. It's easier to maintain framework bindings separately.

We'll happily expose any internal functionality that makes these bindings easier, but supporting bindings for every popular framework is not something we can do on our own. That's where the community comes in, and that's why open source is so great. If members of the Parse community want to drive the development of top-notch Angular bindings, we'll support them in every way we can.

**Comment by ptarjan** [comment]
I've been happily using https://github.com/brandid/parse-angular-patch . It was broken by the 1.6.0 update, but if you are willing to stay at 1.5.0 you can use that.

**Comment by 5amfung** [comment]
Does anyone know how to ```require('parse')``` in angular code?

**Comment by gfpacheco** [comment]
@5amfung if you are loading the `parse.js` file to your html `Parse` will be a globally available var.

**Comment by 5amfung** [comment]
@gfpacheco Thanks for the reply.  Not sure if you're familiar with ionic 2, but my tech stack is ionic 2, angular 2, and webpack.  With the default webpack setup, any ```npm install```ed library that is written for angular is automatically picked up and included in the final bundle.  I'm just not sure how to get Parse sdk included.  It might be something very simple to do but unfortunately I'm a newbie in javascript.

**Comment by gfpacheco** [comment]
@5amfung If that's the case I suggest you to ask on StackOverflow and show off your webpack config and relevant code

**Comment by cleever** [comment]
With the raise of ionic framework with is bundled with Angular. And the notice that angular patch repository was discontinued.
https://github.com/brandid/parse-angular-patch

A oficial support for angular would be very helpful for all comunity.
