### ISSUE TITLE
how to get deleted items from parse platform database?

### ISSUE THREAD

**Issue by hernanbruno97** [parse-community/Parse-SDK-JS#838]
I'm working on an application that requires offline operation, and the Parse local datastore not work for me. when some change occurs while the application is closed, that is, the subscriptions are not active, i can get created and updated items, but in case of deleted items, i cant recover them. any idea about how to solve this

I thought about creating a field that records the date it was "removed", and using it as a filter to remove them from my application
```       
        const createdAt = new Parse.Query("AnyClass");
        createdAt.greaterThan("createdAt", new Date(1560443963000));

        const updatedAt = new Parse.Query("AnyClass");
        updatedAt.greaterThan("updatedAt",  new Date(1560443963000) );

        const mainQuery = Parse.Query.or(createdAt, updatedAt);
        mainQuery.find().then((result)=>{
             // results include created and updated items
        })

        // deleted at ???...
```

**Comment by dplewis** [comment]
I’m a little confused. Do you mean the delete event for subscriptions isn’t working? 

Can you post a code example of what you want to happen? Your code doesn’t have subscriptions in it.

**Comment by TomWFox** [comment]
@hernanbruno97 if the records have been deleted then you can’t recover them unless you have a backup of your database, I think it would defeat the purpose if you could?

Alternatively rather than actually deleting records you could have a class which stores pointers to the records that should be deleted along with the date that they should actually be deleted. The you could use a Cloud Code Job to actually delete the records when the current date has exceeded they ‘deletion date’.

If you have further code level questions please ask them on Stack Overflow with the `parse-platform` tag.
